# Generated by Django 6.0.4 on 2026-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('illness', models.CharField(max_length=200)),
                ('prescription', models.TextField()),
                ('bill_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
