# Generated by Django 6.0.4 on 2026-04-18 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
